### PR TITLE
EventBridge event support and Typedocs

### PR DESCRIPTION
**Pull request by jackholmes1010**
- Added support for `@EventBridge()` decorator for EventBridge Lambda events
- Added `docs` using Typedoc that can be generated using `npm run docs`
- Published docs to GH pages

https://vacasaoss.github.io/lambaa/index.html

### CODE REVIEW

**Review by ngonzalezromero — APPROVED** [review]
Cool

**Review by johnyherangi — APPROVED** [review]
Nice.

**Comment by johnmikk** [comment]
@jackholmes1010 Will this mean that you need to `npm run doc` & commit if any comments are changed?  Or is there some automatic way the doc gets generated?

**Comment by jackholmes1010** [comment]
> @jackholmes1010 Will this mean that you need to `npm run doc` & commit if any comments are changed? Or is there some automatic way the doc gets generated?

At the moment, yeah you need to run `npm run doc` to regenerate. It should probably be automated tho.

**Review by johnmikk — APPROVED** [review]
👍 👍

**Pull request merged**
