### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by johnmikk**
`npm upgrade`

### CODE REVIEW

**Review by jackholmes1010 — APPROVED** [review]

**Review by johnyherangi — APPROVED** [review]

**Comment by victorshi** [comment]
Nice work, @johnmikk. 👍
and good review @jackholmes1010  & @johnyherangi   🙌
@c-moss are you still working?

**Comment by johnmikk** [comment]
> Nice work, @johnmikk. 👍
> and good review @jackholmes1010 & @johnyherangi 🙌
> @c-moss are you still working?

lol, thanks Victor!  You should start using Lambaa 🐑 🚀

**Comment by lisamckinley** [comment]
what am I looking at

**Comment by wverkley-serko** [comment]
Nice to see you folks busy; @johnmikk , @jackholmes1010 , @johnyherangi

**Comment by victorshi** [comment]
@wverkley-serko Hey Wilfred, good to see you here. How's your new life in Serko? It seems you have a lot of free time to browse different public repos. If you don't find your job is challenging enough, nib always needs good developers and we know how to keep them busy 😄

**Pull request merged**
