### PR TITLE
Feature/custom parameter decorator

### PR DESCRIPTION
**Pull request by ngonzalezromero**
## Description

Added support for the creation of custom Params Decorators

### Example

```ts
export const AwesomeParam = CreateParam<boolean>((e: APIGatewayEvent) => {
    return e.isBase64Encoded;
});
```

## Benefits

We can get parameter with custom data in the contollers
```ts
@Controller()
export class AwesomeController {
    @GET("/api/v1/ping)
    public ping( @AwesomeParam() data): Promise<boolean> {
        return data
    }
}
```

### CODE REVIEW

**Review by johnmikk — COMMENTED** [review]
I really like the concept.  Just wondering about the naming of `@CreateParam` for the decorator etc.  How about `@DecodedParam`  or `@ConvertParam`?

**Review by jackholmes1010 — APPROVED** [review]
Nice, looks good. I second John's feedback re naming.

**Comment by ngonzalezromero** [comment]
Hi @johnmikk renamed to DecodedParam

**Review by johnmikk — APPROVED** [review]
Awesome work :100:

**Review by oyanezm — APPROVED** [review]

**Pull request merged**
